/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.awt.Toolkit;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;

import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTextField;

/**
 *
 * @author elmes
 */
public class Calculadora extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora.class.getName());

    // Variables para la lógica de la calculadora
    String numero1;
    String numero2;
    String operador;
    boolean esDecimal = false;

    // Declaración de los componentes de la interfaz
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton5;
    private JButton jButton6;
    private JButton jButton7;
    private JButton jButton8;
    private JButton jButton9;
    private JButton jButton10;
    private JButton jButton11;
    private JButton jButton12;
    private JButton jButton13;
    private JButton jButton14;
    private JButton jButton15;
    private JButton jButton16;
    private JButton jButton17;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenuBar jMenuBar1;
    private JMenuItem jMenuItemHistorial;
    private JMenuItem jMenuItemManual;
    private JMenuItem jMenuItemNuevo;
    private JTextField txtPantalla;

    /**
     * Creates new form CalculadorForm
     */
    public Calculadora() {
        initComponents();
    }

    // Método para reproducir el sonido "beep"
    private void hacerBeep() {
        Toolkit.getDefaultToolkit().beep();
    }

    // Método para escribir en el archivo de bitácora
    private void escribirBitacora(String texto) {
        try (FileWriter fw = new FileWriter("bitacoraCalculadora.txt", true);
             BufferedWriter bw = new BufferedWriter(fw)) {
            bw.write(texto + "\n");
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al escribir en la bitácora: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        // Creación manual de todos los componentes
        txtPantalla = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemHistorial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        txtPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPantalla.setText("0");
        txtPantalla.setFocusable(false);
        txtPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantallaActionPerformed(evt);
            }
        });

        // Eventos para botones numéricos y el punto
        jButton1.setText("0");
        jButton1.addActionListener(this::jButtonNumerosActionPerformed);
        jButton2.setText("9");
        jButton2.addActionListener(this::jButtonNumerosActionPerformed);
        jButton5.setText("5");
        jButton5.addActionListener(this::jButtonNumerosActionPerformed);
        jButton6.setText("6");
        jButton6.addActionListener(this::jButtonNumerosActionPerformed);
        jButton7.setText("7");
        jButton7.addActionListener(this::jButtonNumerosActionPerformed);
        jButton8.setText("8");
        jButton8.addActionListener(this::jButtonNumerosActionPerformed);
        jButton9.setText("1");
        jButton9.addActionListener(this::jButtonNumerosActionPerformed);
        jButton10.setText("2");
        jButton10.addActionListener(this::jButtonNumerosActionPerformed);
        jButton11.setText("3");
        jButton11.addActionListener(this::jButtonNumerosActionPerformed);
        jButton12.setText("4");
        jButton12.addActionListener(this::jButtonNumerosActionPerformed);
        jButton17.setText(".");
        jButton17.addActionListener(this::jButtonPuntoActionPerformed);

        // Eventos para operadores
        jButton13.setText("/");
        jButton13.addActionListener(this::jButtonOperadorActionPerformed);
        jButton14.setText("*");
        jButton14.addActionListener(this::jButtonOperadorActionPerformed);
        jButton15.setText("-");
        jButton15.addActionListener(this::jButtonOperadorActionPerformed);
        jButton16.setText("+");
        jButton16.addActionListener(this::jButtonOperadorActionPerformed);

        // Evento para el botón igual
        jButton3.setText("=");
        jButton3.addActionListener(this::jButtonIgualActionPerformed);

        // Configuración del menú
        jMenu1.setText("Opciones");
        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(this::jMenuItemNuevoActionPerformed);
        jMenu1.add(jMenuItemNuevo);
        jMenuItemHistorial.setText("Historial");
        jMenuItemHistorial.addActionListener(this::jMenuItemHistorialActionPerformed);
        jMenu1.add(jMenuItemHistorial);
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuItemManual.setText("Manual de Usuario");
        jMenuItemManual.addActionListener(this::jMenuItemManualActionPerformed);
        jMenu2.add(jMenuItemManual);
        jMenuBar1.add(jMenu2);
        setJMenuBar(jMenuBar1);

        // Configuración del layout (organización de los componentes)
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11)
                    .addComponent(jButton16))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton12)
                                    .addComponent(jButton5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton2)
                            .addComponent(jButton14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton17)
                            .addComponent(jButton3)
                            .addComponent(jButton13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addGap(89, 89, 89))
        );
        pack();
    }

    private void jButtonNumerosActionPerformed(java.awt.event.ActionEvent evt) {
        hacerBeep();
        javax.swing.JButton boton = (javax.swing.JButton) evt.getSource();
        String textoBoton = boton.getText();
        String textoPantalla = txtPantalla.getText();

        if (textoPantalla.equals("0")) {
            txtPantalla.setText(textoBoton);
        } else {
            txtPantalla.setText(textoPantalla + textoBoton);
        }
        escribirBitacora(textoBoton);
    }

    private void jButtonPuntoActionPerformed(java.awt.event.ActionEvent evt) {
        hacerBeep();
        if (!esDecimal) {
            txtPantalla.setText(txtPantalla.getText() + ".");
            esDecimal = true;
            escribirBitacora(".");
        }
    }

    private void jButtonOperadorActionPerformed(java.awt.event.ActionEvent evt) {
        hacerBeep();
        javax.swing.JButton boton = (javax.swing.JButton) evt.getSource();
        operador = boton.getText();
        numero1 = txtPantalla.getText();
        txtPantalla.setText("");
        esDecimal = false;
        escribirBitacora(operador);
    }

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {
        hacerBeep();
        numero2 = txtPantalla.getText();
        if (numero1 != null && numero2 != null && operador != null) {
            double num1 = Double.parseDouble(numero1);
            double num2 = Double.parseDouble(numero2);
            double resultado = 0;

            switch (operador) {
                case "+":
                    resultado = num1 + num2;
                    break;
                case "-":
                    resultado = num1 - num2;
                    break;
                case "*":
                    resultado = num1 * num2;
                    break;
                case "/":
                    if (num2 != 0) {
                        resultado = num1 / num2;
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "No se puede dividir por cero.");
                        return;
                    }
                    break;
            }
            txtPantalla.setText(String.valueOf(resultado));
            escribirBitacora(numero2);
            escribirBitacora(String.valueOf(resultado));
            numero1 = null;
            numero2 = null;
            operador = null;
        }
    }

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {
        hacerBeep();
        txtPantalla.setText("0");
        numero1 = null;
        numero2 = null;
        operador = null;
        esDecimal = false;
        escribirBitacora("Nuevo");
    }

    private void jMenuItemHistorialActionPerformed(java.awt.event.ActionEvent evt) {
        hacerBeep();
        java.awt.EventQueue.invokeLater(() -> new HistorialForm().setVisible(true));
    }

    private void jMenuItemManualActionPerformed(java.awt.event.ActionEvent evt) {
        hacerBeep();
        javax.swing.JOptionPane.showMessageDialog(this, "Manual de Usuario:\n\n"
                + "Presione los botones numéricos o use el teclado para ingresar números.\n"
                + "Use los botones de operadores para realizar operaciones.\n"
                + "La opción 'Nuevo' en el menú 'Opciones' reinicia la calculadora.\n"
                + "La opción 'Historial' muestra las operaciones realizadas.\n"
                + "Todas las operaciones se guardan en el archivo 'bitacoraCalculadora.txt'.");
    }

    private void txtPantallaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Calculadora().setVisible(true));
    }
}