/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author elmes
 */
public class HistorialForm extends javax.swing.JFrame {

    // Declaración de los componentes de la interfaz
    private JScrollPane jScrollPane1;
    private JTextArea jTextAreaHistorial;

    /**
     * Creates new form HistorialForm
     */
    public HistorialForm() {
        initComponents();
        cargarHistorial();
    }

    private void cargarHistorial() {
        try (FileReader fr = new FileReader("bitacoraCalculadora.txt");
             BufferedReader br = new BufferedReader(fr)) {
            String linea;
            StringBuilder historial = new StringBuilder();
            while ((linea = br.readLine()) != null) {
                historial.append(linea).append("\n");
            }
            jTextAreaHistorial.setText(historial.toString());
        } catch (IOException e) {
            jTextAreaHistorial.setText("No se pudo cargar el historial: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHistorial = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial de Operaciones");

        jTextAreaHistorial.setEditable(false);
        jTextAreaHistorial.setColumns(20);
        jTextAreaHistorial.setRows(5);
        jScrollPane1.setViewportView(jTextAreaHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new HistorialForm().setVisible(true));
    }
}